# Generated by Django 3.1.2 on 2020-10-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mileage', models.IntegerField(default=0)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('seats', models.IntegerField(default=0)),
                ('luggage', models.IntegerField(default=0)),
                ('fuel', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Liquefied Petroleum', 'Liquefied Petroleum'), ('Compressed Natural Gas', 'Compressed Natural Gas'), ('Ethanol', 'Ethanol'), ('Bio-diesel', 'Bio-diesel')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='rental_exchange/car_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CARS',
                'db_table': 'cars',
                'ordering': ('created_at',),
            },
        ),
    ]
