# Generated by Django 3.1.2 on 2020-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0003_car_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='tags',
        ),
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
