# Generated by Django 3.1.2 on 2020-10-10 16:41

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0004_auto_20201010_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rental_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14),
        ),
    ]
