# Generated by Django 3.1.2 on 2020-10-10 16:43

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0006_auto_20201010_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rental_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
    ]
