# Generated by Django 3.1.2 on 2020-11-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0007_auto_20201119_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rental_exchange/car_images'),
        ),
    ]
