# Generated by Django 3.1.2 on 2020-11-23 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0008_auto_20201119_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('client_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('client_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('car_title', models.CharField(max_length=255, verbose_name='Car Title')),
                ('car_model', models.CharField(max_length=50, verbose_name='Car Model')),
                ('model_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2020)])),
                ('message', models.TextField(blank=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CAR REGISTRATION REQUESTS',
                'db_table': 'car_registration_request',
                'ordering': ('created_at',),
            },
        ),
    ]
