# Generated by Django 3.1.2 on 2020-10-10 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0009_car_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TAGS',
                'db_table': 'tags',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='car',
            name='model_no',
            field=models.CharField(default='522', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(default=1984, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2020)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('name', 'model_no', 'model_year')},
        ),
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rental_exchange.Tag'),
        ),
    ]
