# Generated by Django 3.1.2 on 2020-11-27 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_exchange', '0010_auto_20201127_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbooking',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'CAR BOOKINGS'},
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
