# Generated by Django 3.1.2 on 2020-11-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0014_auto_20201128_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregistrationrequest',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
