# Generated by Django 3.1.2 on 2020-11-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0016_auto_20201129_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental_exchange.carbooking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
