# Generated by Django 3.1.2 on 2020-11-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0017_auto_20201129_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='vehicle_owner',
        ),
    ]
