# Generated by Django 3.1.2 on 2020-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0020_auto_20201129_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='agreement_paper',
            field=models.FileField(blank=True, null=True, upload_to='rental_exchange/agreement_papers/'),
        ),
        migrations.AddField(
            model_name='car',
            name='fitness_test',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
